### ISSUE TITLE
MP3 playback wong

### ISSUE THREAD

**Issue by probonopd** [JoshuaD84/HypnosMusicPlayer#1]
Trying to play back https://archive.org/download/testmp3testfile/mpthreetest.mp3 using http://hypnosplayer.org/download/beta1/Hypnos-nix-64bit-beta1.AppImage on Xubuntu 16.04 gives a very high-pitch voice, not how it should sound.

**Comment by JoshuaD84** [comment]
Bug confirmed on my XUbuntu 16.10, working on it. Thanks!

**Comment by JoshuaD84** [comment]
The issue is in playback of all mono mp3s. I have a working solution on hand, should be able to integrate it in the next release.

**Comment by JoshuaD84** [comment]
Fixed in commit #e83354f. Will be included in next release.
