### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [JoshuaD84/HypnosMusicPlayer#2]
#### Issue description

Does not run on Ubuntu 14.04

#### Steps to reproduce the issue

1. Download the Ubuntu 14.04 Live ISO
2. Try to run the Hypnos AppImage

#### What's the expected result?

Runs

#### What's the actual result?

```
libglass.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found
```

#### What's your operating system?

Ubuntu 14.04

#### Additional Details / Screenshots

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

#### Paste Hypnos Log Here

https://travis-ci.org/AppImage/appimage.github.io/builds/456536549#L612

#### Reference

https://github.com/AppImage/appimage.github.io/pull/946

**Comment by JoshuaD84** [comment]
Thank you. I mistakenly thought Ubuntu 14.04 went out of support when 18.04 was released. Looks like we still have a few months. I'll see if I can get this patched in.

**Comment by JoshuaD84** [comment]
I don't know that there's much I can do about this. libglass.so is a javafx library.

**Comment by JoshuaD84** [comment]
For now, with app-images, I've decided not to dedicate the resources to Ubuntu 14.04.  It reached end of standard life in April 2019.

**Comment by probonopd** [comment]
Yes, now the new baseline is xenial.
